//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public string BillID { get; set; }
        public System.DateTime Date { get; set; }
        public string ClientID { get; set; }
        public double ExPrice { get; set; }
        public double ImPrice { get; set; }
        public double Total { get; set; }
    }
}
